main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library_blog.urls')),
    path('', include('books_tags.urls')),
    path('', include('Basket.urls')),
    path('', include('parser_app.urls')),
    path('', include('users.urls')),
    path('', include('ingredients.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ingredients/models.py
from django.db import models


class Recipe(models.Model):
    title = models.TextField(verbose_name='название рецепта')
    description = models.CharField(max_length=100, verbose_name='описание рецепта')

    def __str__(self):
        return self.title

class Ingredient(models.Model):
    UNIT = (
        ("граммы", "граммы"),
        ("килограммы", "килограммы"),
        ("миллилитры", "миллилитры"),
        ("литры", "литры"),
        ("штуки", "штуки")
    )

    name = models.CharField(max_length=100, verbose_name="название ингредиента", null=True)
    quantity = models.IntegerField()
    unit = models.CharField(max_length=50, choices=UNIT, null=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    is_optional = models.BooleanField(default=False)
    calories = models.FloatField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.name} {self.quantity} {self.unit}"


class Collection(models.Model):
    name = models.CharField(max_length=100)
    recipes = models.ManyToManyField(Recipe, related_name='collections')
    def __str__(self):
        return self.name

templates/recipes/recipe_delete.html
<form method="POST">
{% csrf_token %}
<h2>Вы уверенны что хотите удалить </h2>
<button type="submit">Да</button>
<button><a href="{% url 'recipe_list' %}">Нет</a></button>
</form>

templates/recipes/recipe_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ recipe.title }}</title>
</head>
<body>
    <h1>{{ recipe.title }}</h1>
    <p>{{ recipe.description }}</p>
    <h3>Ингредиенты:</h3>
    <ul>
        {% for ingredient in recipe.ingredient_set.all %}
            <li>{{ ingredient.name }}: {{ ingredient.quantity }} {{ ingredient.unit }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'recipe_list' %}">Назад к списку рецептов</a>
</body>
</html>

templates/recipes/recipe_form.html
<h1>Добавить рецепт</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать</button>
</form>

templates/recipes/recipe_list.html
<form method="get" action="{% url 'recipe_list' %}">
    <input type="text" name="q" placeholder="Поиск рецептов..." value="{{ query }}">
    <button type="submit">Найти</button>
</form>

<ul>
    {% for recipe in recipes %}
        <li><a href="{% url 'recipe_detail' recipe.id %}">{{ recipe.title }}</a></li>
        <a href="/recipe/{{recipe.id}}/delete/">Удаление</a>
    {% endfor %}
</ul>